services:
  frontend:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_FRONTEND_REPO}:frontend-latest"
    ports:
      - "80:80"
    depends_on:
      - backend
    mem_limit: 256m

  backend:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_BACKEND_REPO}:backend-latest"
    mem_limit: 1g
    environment:
      POSTGRES_DB_URL: "${POSTGRES_DB_URL}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      S3_REGION: "${AWS_REGION}"
      S3_BUCKET_NAME: "${S3_BUCKET_NAME}"
      CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS}"

