CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE decks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255),
    is_public  BOOLEAN NOT NULL DEFAULT FALSE,
    user_id    BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_decks_user_name UNIQUE (user_id, name),
    CONSTRAINT fk_decks_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE mediametadata (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   VARCHAR(255),
    s3_key                 TEXT,
    presigned_download_url TEXT,
    url_expires_at         TIMESTAMP(6) WITH TIME ZONE,
    created_at             TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE flashcards (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question                   VARCHAR(255),
    answer                     VARCHAR(255),
    deck_id                    BIGINT,
    question_media_metadata_id BIGINT,
    answer_media_metadata_id   BIGINT,
    stability                  DOUBLE PRECISION,
    difficulty                 DOUBLE PRECISION,
    state                      SMALLINT,
    step                       INTEGER,
    due_date                   TIMESTAMP(6) WITH TIME ZONE,
    last_review                TIMESTAMP(6) WITH TIME ZONE,
    created_at                 TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT flashcards_state_check        CHECK (state >= 0 AND state <= 2),
    CONSTRAINT uk_flashcards_question_media  UNIQUE (question_media_metadata_id),
    CONSTRAINT uk_flashcards_answer_media    UNIQUE (answer_media_metadata_id),
    CONSTRAINT fk_flashcards_deck            FOREIGN KEY (deck_id)                    REFERENCES decks (id),
    CONSTRAINT fk_flashcards_question_media  FOREIGN KEY (question_media_metadata_id) REFERENCES mediametadata (id),
    CONSTRAINT fk_flashcards_answer_media    FOREIGN KEY (answer_media_metadata_id)   REFERENCES mediametadata (id)
);

CREATE TABLE shared_decks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id    BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    sharer_id  BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_shared_decks_deck_user UNIQUE (deck_id, user_id),
    CONSTRAINT fk_shared_decks_deck      FOREIGN KEY (deck_id)   REFERENCES decks (id),
    CONSTRAINT fk_shared_decks_user      FOREIGN KEY (user_id)   REFERENCES users (id),
    CONSTRAINT fk_shared_decks_sharer    FOREIGN KEY (sharer_id) REFERENCES users (id)
);

CREATE TABLE daily_study_progress (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    new_cards_studied    INTEGER NOT NULL,
    review_cards_studied INTEGER NOT NULL,
    study_date           DATE NOT NULL,
    deck_id              BIGINT NOT NULL,
    user_id              BIGINT NOT NULL,
    CONSTRAINT uk_daily_study_progress_user_deck UNIQUE (user_id, deck_id),
    CONSTRAINT fk_daily_study_progress_user      FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_daily_study_progress_deck      FOREIGN KEY (deck_id) REFERENCES decks (id)
);

CREATE TABLE user_settings (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT NOT NULL,
    daily_new_card_limit  INTEGER NOT NULL DEFAULT 20,
    daily_review_limit    INTEGER NOT NULL DEFAULT 200,
    review_ahead_minutes  INTEGER NOT NULL DEFAULT 20,
    CONSTRAINT uk_user_settings_user UNIQUE (user_id),
    CONSTRAINT fk_user_settings_user FOREIGN KEY (user_id) REFERENCES users (id)
);
